name: enpkg_publication_examples
channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - plotly
  - tmap
dependencies:
  - python==3.7
  - tmap
  - sparqlwrapper
  - rdkit
  - scikit-learn
  - plotly
  - ipython
  - ipykernel
  - matplotlib
  - umap-learn
  - pip
  - pip:
    - git+https://github.com/reymond-group/map4
    - mhfp
    - datatable
